<a href="https://colab.research.google.com/github/meenaxchidambaram/LinearAlgebraHW01/blob/Q6/Welcome_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra HW 01 - Part B: Q6

In [1]:
import numpy as np

In [2]:
# Set print options for better readability of the output arrays
np.set_printoptions(suppress=True, precision=4)

In [3]:
# 1. Define the matrix A
A = np.array([
    [1, 2, 0, 2, 1],
    [3, 6, 1, 9, 6],
    [2, 4, 1, 7, 5]
])

In [5]:
# 2. Use an in-built function to compute the SVD
# U: Unitary matrix (m x m). The columns are the left-singular vectors.
# s: 1-D array of singular values of A.
# Vh: Unitary matrix (n x n) (V transpose). The rows are the right-singular vectors.
U, s, Vh = np.linalg.svd(A)

In [7]:
s

array([16.3332,  1.1071,  0.    ])

In [6]:
# 3. Determine the rank from the singular values
# The rank is the number of non-zero singular values.
# We use a small tolerance to account for floating-point inaccuracies.
tolerance = 1e-10
rank = np.sum(s > tolerance)

In [8]:
# 4. Compute the bases for the four fundamental subspaces from U and Vh
# V is the transpose of Vh
V = Vh.T
m, n = A.shape

In [9]:
# Basis for the Column Space C(A)
# The first 'rank' columns of U
col_space_basis = U[:, :rank]

# Basis for the Row Space C(A^T)
# The first 'rank' columns of V
row_space_basis = V[:, :rank]

# Basis for the Null Space N(A)
# The last 'n - rank' columns of V
null_space_basis = V[:, rank:]

# Basis for the Left Null Space N(A^T)
# The last 'm - rank' columns of U
left_null_space_basis = U[:, rank:]

In [11]:
print("Original Matrix A:")
print(A)
print("\n" + "-"*40)
print(f"Shape of A: (m, n) = {A.shape}")
print(f"Singular values (s): {s}")
print(f"Rank of A (r): {rank}")
print("-" * 40 + "\n")

print("## Basis for the Column Space, C(A)")
print("A basis is formed by the first r columns of U.")
print(f"Dimension = r = {col_space_basis.shape[1]}")
print(col_space_basis)
print("\n" + "-"*40 + "\n")

print("## Basis for the Row Space, C(A^T)")
print("A basis is formed by the first r columns of V.")
print(f"Dimension = r = {row_space_basis.shape[1]}")
print(row_space_basis)
print("\n" + "-"*40 + "\n")

print("## Basis for the Null Space, N(A)")
print("A basis is formed by the last n-r columns of V.")
print(f"Dimension = n - r = {null_space_basis.shape[1]}")
print(null_space_basis)
print("\n" + "-"*40 + "\n")

print("## Basis for the Left Null Space, N(A^T)")
print("A basis is formed by the last m-r columns of U.")
print(f"Dimension = m - r = {left_null_space_basis.shape[1]}")
print(left_null_space_basis)

Original Matrix A:
[[1 2 0 2 1]
 [3 6 1 9 6]
 [2 4 1 7 5]]

----------------------------------------
Shape of A: (m, n) = (3, 5)
Singular values (s): [16.3332  1.1071  0.    ]
Rank of A (r): 2
----------------------------------------

## Basis for the Column Space, C(A)
A basis is formed by the first r columns of U.
Dimension = r = 2
[[-0.186   0.795 ]
 [-0.7815  0.2365]
 [-0.5955 -0.5586]]

----------------------------------------

## Basis for the Row Space, C(A^T)
A basis is formed by the first r columns of V.
Dimension = r = 2
[[-0.2279  0.3499]
 [-0.4557  0.6997]
 [-0.0843 -0.2909]
 [-0.7086 -0.1731]
 [-0.4808 -0.5229]]

----------------------------------------

## Basis for the Null Space, N(A)
A basis is formed by the last n-r columns of V.
Dimension = n - r = 3
[[-0.0771 -0.7583 -0.4947]
 [ 0.2659  0.1301  0.4638]
 [ 0.9351 -0.1059 -0.1503]
 [-0.1429  0.4628 -0.483 ]
 [-0.1688 -0.4275  0.5331]]

----------------------------------------

## Basis for the Left Null Space, N(A^T)
